"""Endpoint: deterministic, evidence-backed security findings for a
given repository or an already-created analysis session (Phase 7E;
extended by Phase 9 and Phase 10).

ARCHITECTURAL RULE: this router does not decide what counts as a
finding — it only validates the request shape and calls
app.services.security_service, which delegates to app.security.rules'
and app.security.attack_surface's fixed rule functions. No LLM is
involved anywhere in this endpoint: the deterministic rule engine
decides every finding; this router just maps each
app.explanation.evidence.Observation (kind=SECURITY_FINDING) it gets
back into the public SecurityFinding/SecurityResponse shape below.

Accepts EITHER `repo_url` (fresh clone/scan/build) OR `analysis_id`
(reuse an already-built analysis from a prior POST /analyze) — the same
mutual-exclusivity validator pattern already established in
explain.py/components.py/impact.py/dependencies.py/graph_diagnostics.py.

Phase 10: adds a static, deterministic `remediation` hint per finding —
a fixed, one-line suggested fix looked up by `rule_id` alone, exactly
like `title` already is. Not generated by an LLM, not customized per
repository — the same "deterministic engine decides, this router only
presents" discipline the rest of this endpoint already follows. Every
one of the 10 rule_ids that currently exist (5 from app.security.rules'
Phase 7E rules, 4 from its Phase 7G rules, 1 from
app.security.attack_surface's Phase 9 rule) has a real, specific entry
below — the generic fallback exists only as a defensive default for a
future rule_id this mapping hasn't been updated for yet, not as the
normal case.
"""

from fastapi import APIRouter
from pydantic import BaseModel, Field, model_validator

from app.services import security_service

router = APIRouter()

_DEFAULT_REMEDIATION = "Review this finding and apply an appropriate fix for the underlying configuration."

_REMEDIATION_BY_RULE_ID: dict[str, str] = {
    "MUTABLE_IMAGE_TAG": (
        "Pin the image to a specific version tag or digest (e.g. 'myapp:1.2.3' or "
        "'myapp@sha256:...') instead of ':latest' or an implicit tag."
    ),
    "HARDCODED_SECRET_ENV_VAR": (
        "Move this value out of the file and inject it via a secret manager, a local "
        "'.env' file (excluded from version control), or a CI/CD secret variable."
    ),
    "DOCKER_SOCKET_MOUNT": (
        "Remove the Docker socket bind-mount. If container management from inside a "
        "container is genuinely required, use a scoped Docker API proxy instead of the "
        "raw socket."
    ),
    "DATABASE_PORT_PUBLISHED": (
        "Remove the host port mapping for this database service so it's reachable only "
        "from other services on the same internal network."
    ),
    "SENSITIVE_PORT_PUBLISHED": (
        "Remove the host port mapping for this administrative port, or restrict it to a "
        "trusted source IP range if external access is genuinely required."
    ),
    "INGRESS_WITHOUT_TLS": "Add a 'tls' block to this Ingress referencing a valid TLS certificate Secret.",
    "EXTERNALLY_REACHABLE_SERVICE": (
        "Confirm external reachability is intentional. If not, change the Service type to "
        "'ClusterIP' and front it with an Ingress instead."
    ),
    "PRIVILEGED_CONTAINER": (
        "Remove 'privileged: true' from this container's securityContext, or replace it "
        "with the specific Linux capability actually required."
    ),
    "CONTAINER_ALLOWED_TO_RUN_AS_ROOT": (
        "Set 'runAsNonRoot: true' in this workload's securityContext (at the pod or "
        "container level)."
    ),
    "EXPOSED_PATH_TO_SECRET": (
        "Add TLS to the exposing Ingress and/or restrict the Service's exposure, or apply "
        "a NetworkPolicy limiting which sources can reach this workload."
    ),
}


class SecurityAPIRequest(BaseModel):
    """Request body for POST /security — just an analysis source, no
    other parameters: every rule scans the whole resolved analysis."""

    repo_url: str | None = Field(
        default=None, description="Public GitHub repository URL to analyze. Mutually exclusive with analysis_id."
    )
    analysis_id: str | None = Field(
        default=None,
        description=(
            "Id of an analysis session already created via POST /analyze (Phase 7A). Reuses "
            "that exact analysis instead of triggering a fresh clone/scan. Mutually exclusive "
            "with repo_url."
        ),
    )

    @model_validator(mode="after")
    def _check_exactly_one_analysis_source(self) -> "SecurityAPIRequest":
        if (self.repo_url is None) == (self.analysis_id is None):
            raise ValueError("Provide exactly one of repo_url or analysis_id.")
        return self


class SecurityFinding(BaseModel):
    """One deterministic security finding, built entirely from an
    Observation's own fields — see app.security.rules for exactly which
    parsed metadata field proves each rule's condition."""

    rule_id: str = Field(..., description="Which rule produced this finding, e.g. 'MUTABLE_IMAGE_TAG'.")
    severity: str = Field(..., description="One of: high, medium, low. Assigned by the fixed rule definition only.")
    title: str = Field(..., description="Short human-readable summary of the finding.")
    reason: str = Field(..., description="The concrete, factual reason this rule fired, citing the actual parsed value.")
    remediation: str = Field(
        ..., description="A static, deterministic suggested fix for this rule_id — not LLM-generated, not repository-specific."
    )
    component_id: str = Field(..., description="The affected Component's id.")
    component_name: str = Field(..., description="The affected Component's name.")
    technology: str = Field(..., description="The affected Component's source technology, e.g. 'docker-compose'.")
    source_file: str | None = Field(default=None, description="The repo-relative file this finding's evidence came from.")


class SecurityResponse(BaseModel):
    """Response body for POST /security."""

    findings: list[SecurityFinding] = Field(default_factory=list)
    total_count: int = Field(..., description="len(findings).")
    counts_by_severity: dict[str, int] = Field(
        default_factory=dict, description="Finding count per severity value present, e.g. {'high': 2, 'medium': 1}."
    )


def _to_security_finding(observation) -> SecurityFinding:  # noqa: ANN001
    detail = observation.detail
    rule_id = detail["rule_id"]
    return SecurityFinding(
        rule_id=rule_id,
        severity=detail["severity"],
        title=detail["title"],
        reason=detail["reason"],
        remediation=_REMEDIATION_BY_RULE_ID.get(rule_id, _DEFAULT_REMEDIATION),
        component_id=observation.subject_id,
        component_name=detail["component_name"],
        technology=detail["technology"],
        source_file=detail.get("source_file"),
    )


@router.post(
    "/security",
    response_model=SecurityResponse,
    summary="Deterministic, evidence-backed security findings",
    responses={
        404: {"description": "The given analysis_id is unknown/expired."},
        422: {"description": "Invalid request: neither repo_url nor analysis_id given, or both given together."},
    },
)
def get_security_findings(request: SecurityAPIRequest) -> SecurityResponse:
    """A plain `def`, not `async def` — same reasoning as every other
    route in this API: resolving an analysis is blocking I/O in the
    fresh-clone case, and FastAPI runs sync handlers in a worker thread
    automatically."""
    observations = security_service.get_security_findings(
        analysis_id=request.analysis_id, repo_url=request.repo_url
    )
    findings = [_to_security_finding(observation) for observation in observations]

    counts_by_severity: dict[str, int] = {}
    for finding in findings:
        counts_by_severity[finding.severity] = counts_by_severity.get(finding.severity, 0) + 1

    return SecurityResponse(findings=findings, total_count=len(findings), counts_by_severity=counts_by_severity)
